version: "3.6"
services:
  web:
    build: web
    image: yannmer/tripmealimages-web:0.1
    networks:
      - backend
    ports:
      - "5000:3000"
    environment:
      DATABASE_NAME: "tripmealdb"
      DATABASE_USER: "root"
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      TRIPMEAL_KEY: "my-secret-key"
      SERVER_PORT: "5000"

  db:
    build: db
    image: yannmer/tripmealimages-db:0.1
    networks:
      - backend
    volumes:
      - tripmeal:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "my-secret-pw"
      POSTGRES_DB: "tripmealdb"

networks:
  backend:

volumes:
  tripmeal:
